# Generated by Django 3.2.18 on 2023-06-06 13:33

from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0079_full_channel_access_group_for_openid"),
        ("app", "0025_auto_20230420_1544"),
        ("discount", "0045_promotion_promotionrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("promotion_created", "Promotion created"),
                            ("promotion_updated", "Promotion updated"),
                            ("promotion_deleted", "Promotion deleted"),
                            ("rule_created", "Rule created"),
                            ("rule_updated", "Rule updated"),
                            ("rule_deleted", "Rule deleted"),
                            ("start", "Start"),
                            ("end", "End"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_events",
                        to="app.app",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="discount.promotion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_events",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
            },
        ),
    ]
