# Generated by Django 3.2.19 on 2023-06-15 12:21

from django.db import migrations
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_merge_20230221_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None),
        ),
    ]
